GET http://localhost:3000/delivery/status/ HTTP/1.1

###

GET http://localhost:3000/delivery/status/68e34bbfb7013041ca327012 HTTP/1.1

###

POST http://localhost:3000/delivery/status/ HTTP/1.1
Content-Type: application/json

{
    "status": "test"
}

###

PUT http://localhost:3000/delivery/status/68e34bbfb7013041ca327012 HTTP/1.1
Content-Type: application/json

{
    "status": "Invoicing"
}

###

DELETE http://localhost:3000/delivery/status/68e34bbfb7013041ca327012 HTTP/1.1