GET http://localhost:3000/delivery/base/ HTTP/1.1

###

GET http://localhost:3000/delivery/base/68e362f28124db413fb5e96e HTTP/1.1

###

POST http://localhost:3000/delivery/base/ HTTP/1.1
Content-Type: application/json

{
    "DeliveryPO": "68d5f654908f41ac12f2746a",
    "DeliverStatus": "68d482c69ff92b31d5a56665",
    "from_address": "test",
    "to_address": "test"
}

###

PUT http://localhost:3000/delivery/base/68e3629d8124db413fb5e95d HTTP/1.1
Content-Type: application/json

{
    "DeliveryPO": "68d5f654908f41ac12f2746a",
    "DeliverStatus": "68d482e09ff92b31d5a56667",
    "from_address": "test",
    "to_address": "test"
}

###

DELETE http://localhost:3000/delivery/base/68e362de8124db413fb5e968 HTTP/1.1