GET http://localhost:3000/delivery/ HTTP/1.1

###

POST http://localhost:3000/delivery/create HTTP/1.1
Content-Type: application/json

{
    "part_no":"test",
    "name":"test",
    "qty":4,
    "unit":"PCS",
    "unit_price":4,
    "tax":4,
    "description":"test"
}